### ISSUE TITLE
First release adocblog-1.0 todo list

### ISSUE THREAD

**Issue by zemian** [zemian/adocblog#1]
TODOs
- [X] Init git repo and Java project
- [X] Setup maven pom for webapp
- [X] Design blog database schema
- [X] Implements Blog and Page UI management
- [X] Add web design for blog viewing
- [X] Add FreeMarker templates
- [X] Add Blog format create/edit drop down
- [X] Add Page format create/edit drop down
- [X] Fix search with validation
- [X] Add ExtClasspathConfigurator for logback
- [X] Add blog get validation
- [X] Improve error message and hide stacktrace from user
- [X] Add pagination to users and settings
- [X] Add page controller get view by docId
- [X] Improve pom build lib/adocblog.jar when packing war
- [X] Add release build package script
- [X] Add script to package zip dist to include sql and adocblog-1.0.war
- [X] Add release.sh scripts
- [X] Add release version properties
- [x] Display version info on system-info page
- [x] Add webapp-runner in dist
- [x] Add Disqus feature to blog view
- [x] Add form validation for create/edit Pages
- [x] Add db conn pool data config
- [x] Add UI/utility to update User Password?
- [x] Add Spring profile for Heroku
- [x] Add adocblog.env to control logging and Spring profile?
- [x] Test deployment on Heroku
